### PR TITLE
Fix 0003-iteration Decision return type

### PR DESCRIPTION
**Pull request by tarilabs**
Based on test case, the return type of the decision is a collection/list
of feel:number.

### CODE REVIEW

**Comment by tarilabs** [comment]
Please use this handy-link to evaluate the changes proposed with this PR, netting the tabs-to-spaces change: https://github.com/agilepro/dmn-tck/pull/16/files?w=1

**Comment by tarilabs** [comment]
cc/ @etirelli

**Comment by agilepro** [comment]
OK, looks alright, and necessary.

I am mystified by the changes to the tabs.   Only the first tab on a line was change, but subsequent tabs left in.  Why?   I have a small preference for always avoiding tabs, but why modify only some of the tabs, and not all of them?

**Comment by tarilabs** [comment]
@agilepro sorry I believe I didn't used the IDE functionality properly, I've added commit 6170432 to address that.

**Comment by etirelli** [comment]
@tarilabs thank you!

**Pull request merged**
